/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.maxkorte;

import org.junit.Test;
import static org.junit.Assert.*;

public class KGVTest {
    @Test
    public void testGetKGV() {
        assertEquals(27, KGV.getKGV(27, 0));
        assertEquals(6, KGV.getKGV(0, 6));
        assertEquals(24, KGV.getKGV(6, 8));
        assertEquals(8, KGV.getKGV(8, 4));
        assertEquals(5681, KGV.getKGV(437, 299));
    }
}
